language: rust
rust: stable

stages:
  - name: tests
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: tests
      name: 'Code checks'
      install:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo fmt -- --check
        - cargo clippy -- -D warnings

    - stage: release
      name: 'Release linux'
      os: linux
      env: TARGET=x86_64-unknown-linux-gnu
      script:
        - cargo build --target "$TARGET" --release
        - mkdir -p ./dist/standup-${TRAVIS_TAG}-$TARGET
        - mv ./target/$TARGET/release/standup_rs ./dist/standup-${TRAVIS_TAG}-$TARGET/
        - tar -cvzf ./dist/standup-${TRAVIS_TAG}-$TARGET.tar.gz ./dist/standup-${TRAVIS_TAG}-$TARGET/
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: ./dist/*.tar.gz
        file_glob: true
        skip_cleanup: true
        on:
          tags: true

    - stage: release
      name: 'Release macOs'
      os: osx
      env: TARGET=x86_64-apple-darwin
      script:
        - cargo build --target "$TARGET" --release
        - mkdir -p ./dist/standup-${TRAVIS_TAG}-$TARGET
        - mv ./target/$TARGET/release/standup_rs ./dist/standup-${TRAVIS_TAG}-$TARGET/
        - tar -cvzf ./dist/standup-${TRAVIS_TAG}-$TARGET.tar.gz ./dist/standup-${TRAVIS_TAG}-$TARGET/
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: ./dist/*.tar.gz
        file_glob: true
        skip_cleanup: true
        on:
          tags: true

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry
